### ISSUE TITLE
[TTR-0006] Don't work in 1.16.5

### ISSUE THREAD

**Issue by Nave13** [PauMAVA/TheTowersRemastered#6] opened 2021-06-02 17:15 UTC
453 / 5000
Résultats de traduction
Hello,

I tried by all means to make the plugins work but it definitely does not want it.

I have followed the steps of the plugins (I use the default map of the plugins)

Everything works fine until I start the plugins with the / ttrenable, I restart the server and nothing works anymore, The plugins appear in red when I do a /pl

After no more command of the plugins works 

I attach you the logs of my server, hoping that it can help you 

(translate with google translater)

[2021-06-02-1.log.gz](https://github.com/PauMAVA/TheTowersRemastered/files/6586370/2021-06-02-1.log.gz)
![tower bug](https://user-images.githubusercontent.com/85248065/120523863-b90d3400-c3d6-11eb-94c4-9ecfe6c23c58.PNG)
![2021-06-02_19 06 23](https://user-images.githubusercontent.com/85248065/120523924-c88c7d00-c3d6-11eb-8cfe-89eb69f8d000.png)

**Comment by Nave13** [comment] 2021-06-02 22:23
I trying with 1.2 and he don't work too 

the logs I sent are in version 1.2

**Comment by PauMAVA** [comment] 2021-06-04 08:49
I see. This is clearly related to #5. I was not able to reproduce this. 

I am going to implement a java Reflection helper to avoid this kind of errors. Will release a patch as soon as possible to fix the error.

**Comment by Nave13** [comment] 2021-06-04 11:09
Thank you very much ! 

it's always nice to see that a project is still updated (even years after it came out) 👍 

I would change my opinion on the plugins on spigot :-)

**Comment by PauMAVA** [comment] 2021-06-04 13:29
I have applied a patch that should solve the error. Can you please confirm that the `.jar` inside this `.zip` works well? (Make sure you delete the old jar).
[TTRUnstable1.2.1.zip](https://github.com/PauMAVA/TheTowersRemastered/files/6598790/TTRUnstable1.2.1.zip)

If this works I will post the release so that everyone can benefit from this bug fix.

**Comment by Nave13** [comment] 2021-06-05 19:30
Hi thanks for the quick response.

I confirm the path works perfectly. I tested it well and everything works !!

I also wanted to ask you if you would like to output a language.yml file for your plugins?

If you want I could translate it to you in French and in Spanish :-)

**Comment by PauMAVA** [comment] 2021-06-06 08:37
Thanks! I will post a resource update on Spigot MC with the patched `.jar`. 

About the `language.yml` I will implement the multilanguage system in `1.3`. When I have the `lang_enEN.yml` file I will let you know so that you may translate it to French and to Spanish 😄 . For now, I will open another issue and assign it to you. 

Please comment something in #8 and #9 so that I can assign those issues to you.

[Here you have the 1.2.1 release](https://github.com/PauMAVA/TheTowersRemastered/releases/tag/v1.2.1)

Also don't forget to correct the SpigotMC review! 😄

**Closed as completed by PauMAVA** 2021-06-06 08:37 UTC
